#!/bin/sh
set -e

. /usr/share/debconf/confmodule

#
# New installation ? then no need to show notice, also not in next upgrades
#
if [ -z "$2" ]; then
	db_fset xfstt/default_port_changed seen true
else
	db_input low xfstt/default_port_changed || true
	db_go || true
fi

if [ -e /etc/default/xfstt ]; then
	. /etc/default/xfstt || true
	
	case "$LISTEN_TCP" in
	yes)	db_set xfstt/listen_tcp true
		;;
	no)	db_set xfstt/listen_tcp false
		;;
	esac
fi

db_input medium xfstt/listen_tcp || true
db_go || true

if [ -e "/var/ttfonts" ]; then
	db_input medium xfstt/fonts_not_supplied || true
	db_go || true
fi

