#!/bin/sh
set -e

. /usr/share/debconf/confmodule

if [ -e /etc/default/xfstt ]; then
  . /etc/default/xfstt || true

  case "$LISTEN_TCP" in
  yes)
    db_set xfstt/listen_tcp true
    ;;
  no)
    db_set xfstt/listen_tcp false
    ;;
  esac
fi

db_input low xfstt/listen_tcp || true
db_go || true
